id: P004581
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG20929
  title: ལྷ་སའི་དམངས་ཁྲོད་སྒྲུང་གཏམ།
  author: ''
  volumes:
    59f797f1275e4fb88815eeee75c521ee:
      image_group_id: I1KG20994
      title: ''
      volume_number: 1
      total_pages: 568
      base_file: v001.txt
    fba7ce8654dc4cc9af6690c66a952cac:
      image_group_id: I1KG20995
      title: ''
      volume_number: 2
      total_pages: 712
      base_file: v002.txt
